name: CI

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install root deps
        run: npm ci
      - name: Install server deps
        run: cd nascon-app/server && npm ci
      - name: Install client deps
        run: cd nascon-app/client && npm ci
      - name: Lint client
        run: cd nascon-app/client && npm run lint --if-present
      - name: Build client
        run: cd nascon-app/client && npm run build --if-present
      - name: Server unit tests
        run: cd nascon-app/server && npm test --if-present

